# .streamlit/config.toml
[server]
maxUploadSize = 200  # MB para archivos
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#2E7D32"
backgroundColor = "#F9F9F9"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#2C3E50"
font = "sans serif"

[runner]
magicEnabled = false
